---
apiVersion: v1
kind: Namespace
metadata:
  name: ngrok-operator
  labels:
    name: ngrok-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    name: demo-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
