---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-app
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/gitops-ngrok-argocd  # Update with your repo URL
    targetRevision: HEAD
    path: apps/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
